name: Android APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend deps
        working-directory: frontend
        run: npm ci

      - name: Build web assets
        working-directory: frontend
        run: npm run build:web

      - name: Install Capacitor CLI
        run: npm install -g @capacitor/cli

      - name: Add Android platform (if missing)
        working-directory: frontend
        run: |
          if [ ! -d "android" ]; then
            npx cap add android || true
          fi

      - name: Copy web assets to native
        working-directory: frontend
        run: |
          npx cap copy android

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK tools
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: google_apis
          ndk: false

      - name: Grant gradle executable
        run: |
          chmod +x frontend/android/gradlew

      - name: Build Release AAB
        run: |
          cd frontend/android
          ./gradlew bundleRelease --no-daemon
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Decode keystore (if provided) and prepare signing file
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 && secrets.KEY_ALIAS && secrets.KEY_PASSWORD && secrets.STORE_PASSWORD }}
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > release_keystore.jks
          cd frontend/android
          echo "storeFile=$(pwd)/release_keystore.jks" > release-keystore.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> release-keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> release-keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> release-keystore.properties

      - name: Upload artifact (AAB)
        uses: actions/upload-artifact@v4
        with:
          name: openlms-android-aab
          path: frontend/android/app/build/outputs/bundle/release/*.aab
